// Auto-generated by scripts/process-client-showroom-images.mjs — do not hand-edit.
// Anonymous, sequentially-named project photos for the /client-showroom page.
export type ShowroomImage = { src: string; width: number; height: number };

export const CLIENT_SHOWROOM_IMAGES: ShowroomImage[] = [
  {
    "src": "/images/client-showroom/photo-0001.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0002.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0003.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0004.jpg",
    "width": 1600,
    "height": 793
  },
  {
    "src": "/images/client-showroom/photo-0005.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0006.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0007.jpg",
    "width": 1174,
    "height": 880
  },
  {
    "src": "/images/client-showroom/photo-0008.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0009.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0010.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0011.jpg",
    "width": 900,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0012.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0013.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0014.jpg",
    "width": 480,
    "height": 320
  },
  {
    "src": "/images/client-showroom/photo-0015.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0016.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0017.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0018.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0019.jpg",
    "width": 1138,
    "height": 756
  },
  {
    "src": "/images/client-showroom/photo-0020.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0021.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0022.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0023.jpg",
    "width": 1600,
    "height": 932
  },
  {
    "src": "/images/client-showroom/photo-0024.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0025.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0026.jpg",
    "width": 675,
    "height": 540
  },
  {
    "src": "/images/client-showroom/photo-0027.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0028.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0029.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0030.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0031.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0032.jpg",
    "width": 1600,
    "height": 1066
  },
  {
    "src": "/images/client-showroom/photo-0033.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0034.jpg",
    "width": 640,
    "height": 426
  },
  {
    "src": "/images/client-showroom/photo-0035.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0036.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0037.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0038.jpg",
    "width": 1174,
    "height": 880
  },
  {
    "src": "/images/client-showroom/photo-0039.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0040.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0041.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0042.jpg",
    "width": 1134,
    "height": 850
  },
  {
    "src": "/images/client-showroom/photo-0043.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0044.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0045.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0046.jpg",
    "width": 1600,
    "height": 1067
  },
  {
    "src": "/images/client-showroom/photo-0047.jpg",
    "width": 1133,
    "height": 753
  },
  {
    "src": "/images/client-showroom/photo-0048.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0049.jpg",
    "width": 800,
    "height": 533
  },
  {
    "src": "/images/client-showroom/photo-0050.jpg",
    "width": 1600,
    "height": 885
  },
  {
    "src": "/images/client-showroom/photo-0051.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0052.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0053.jpg",
    "width": 960,
    "height": 640
  },
  {
    "src": "/images/client-showroom/photo-0054.jpg",
    "width": 1134,
    "height": 850
  },
  {
    "src": "/images/client-showroom/photo-0055.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0056.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0057.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0058.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0059.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0060.jpg",
    "width": 960,
    "height": 622
  },
  {
    "src": "/images/client-showroom/photo-0062.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0063.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0064.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0065.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0066.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0067.jpg",
    "width": 1134,
    "height": 850
  },
  {
    "src": "/images/client-showroom/photo-0068.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0069.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0070.jpg",
    "width": 1174,
    "height": 880
  },
  {
    "src": "/images/client-showroom/photo-0071.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0072.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0073.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0074.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0075.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0076.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0077.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0078.jpg",
    "width": 1126,
    "height": 844
  },
  {
    "src": "/images/client-showroom/photo-0079.jpg",
    "width": 1082,
    "height": 669
  },
  {
    "src": "/images/client-showroom/photo-0080.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0081.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0082.jpg",
    "width": 1600,
    "height": 847
  },
  {
    "src": "/images/client-showroom/photo-0083.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0084.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0085.jpg",
    "width": 900,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0086.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0087.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0088.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0089.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0090.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0091.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0092.jpg",
    "width": 1134,
    "height": 850
  },
  {
    "src": "/images/client-showroom/photo-0093.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0094.jpg",
    "width": 638,
    "height": 850
  },
  {
    "src": "/images/client-showroom/photo-0095.jpg",
    "width": 1600,
    "height": 758
  },
  {
    "src": "/images/client-showroom/photo-0096.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0097.jpg",
    "width": 960,
    "height": 720
  },
  {
    "src": "/images/client-showroom/photo-0098.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0099.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0100.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0101.jpg",
    "width": 1134,
    "height": 850
  },
  {
    "src": "/images/client-showroom/photo-0102.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0103.jpg",
    "width": 960,
    "height": 640
  },
  {
    "src": "/images/client-showroom/photo-0104.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0105.jpg",
    "width": 1600,
    "height": 1195
  },
  {
    "src": "/images/client-showroom/photo-0106.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0107.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0108.jpg",
    "width": 474,
    "height": 574
  },
  {
    "src": "/images/client-showroom/photo-0109.jpg",
    "width": 1600,
    "height": 1066
  },
  {
    "src": "/images/client-showroom/photo-0110.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0111.jpg",
    "width": 1600,
    "height": 1066
  },
  {
    "src": "/images/client-showroom/photo-0112.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0113.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0114.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0115.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0116.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0117.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0118.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0119.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0120.jpg",
    "width": 1600,
    "height": 1066
  },
  {
    "src": "/images/client-showroom/photo-0121.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0122.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0123.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0124.jpg",
    "width": 1600,
    "height": 758
  },
  {
    "src": "/images/client-showroom/photo-0125.jpg",
    "width": 900,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0126.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0127.jpg",
    "width": 1086,
    "height": 672
  },
  {
    "src": "/images/client-showroom/photo-0128.jpg",
    "width": 1443,
    "height": 1162
  },
  {
    "src": "/images/client-showroom/photo-0129.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0130.jpg",
    "width": 640,
    "height": 432
  },
  {
    "src": "/images/client-showroom/photo-0131.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0132.jpg",
    "width": 1600,
    "height": 899
  },
  {
    "src": "/images/client-showroom/photo-0133.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0134.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0135.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0136.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0137.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0138.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0139.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0140.jpg",
    "width": 1134,
    "height": 850
  },
  {
    "src": "/images/client-showroom/photo-0141.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0142.jpg",
    "width": 1600,
    "height": 1057
  },
  {
    "src": "/images/client-showroom/photo-0143.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0144.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0145.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0146.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0147.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0148.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0149.jpg",
    "width": 660,
    "height": 880
  },
  {
    "src": "/images/client-showroom/photo-0150.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0151.jpg",
    "width": 660,
    "height": 880
  },
  {
    "src": "/images/client-showroom/photo-0152.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0153.jpg",
    "width": 1174,
    "height": 880
  },
  {
    "src": "/images/client-showroom/photo-0154.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0155.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0156.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0157.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0158.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0159.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0160.jpg",
    "width": 1600,
    "height": 1067
  },
  {
    "src": "/images/client-showroom/photo-0161.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0162.jpg",
    "width": 1174,
    "height": 880
  },
  {
    "src": "/images/client-showroom/photo-0163.jpg",
    "width": 1600,
    "height": 1067
  },
  {
    "src": "/images/client-showroom/photo-0164.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0165.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0166.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0167.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0168.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0169.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0170.jpg",
    "width": 1132,
    "height": 752
  },
  {
    "src": "/images/client-showroom/photo-0171.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0172.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0173.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0174.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0175.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0176.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0177.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0178.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0179.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0180.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0181.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0182.jpg",
    "width": 1600,
    "height": 1067
  },
  {
    "src": "/images/client-showroom/photo-0183.jpg",
    "width": 1134,
    "height": 850
  },
  {
    "src": "/images/client-showroom/photo-0184.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0185.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0186.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0187.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0188.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0189.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0190.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0191.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0192.jpg",
    "width": 758,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0193.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0194.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0195.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0196.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0197.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0198.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0199.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0200.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0201.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0202.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0203.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0204.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0205.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0206.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0207.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0208.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0209.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0210.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0211.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0212.jpg",
    "width": 1085,
    "height": 722
  },
  {
    "src": "/images/client-showroom/photo-0213.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0214.jpg",
    "width": 1600,
    "height": 1066
  },
  {
    "src": "/images/client-showroom/photo-0215.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0216.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0217.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0218.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0219.jpg",
    "width": 377,
    "height": 707
  },
  {
    "src": "/images/client-showroom/photo-0220.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0221.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0222.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0223.jpg",
    "width": 1350,
    "height": 1080
  },
  {
    "src": "/images/client-showroom/photo-0224.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0225.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0226.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0227.jpg",
    "width": 1174,
    "height": 880
  },
  {
    "src": "/images/client-showroom/photo-0228.jpg",
    "width": 1174,
    "height": 880
  },
  {
    "src": "/images/client-showroom/photo-0229.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0230.jpg",
    "width": 1286,
    "height": 857
  },
  {
    "src": "/images/client-showroom/photo-0231.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0232.jpg",
    "width": 1087,
    "height": 670
  },
  {
    "src": "/images/client-showroom/photo-0233.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0234.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0235.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0236.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0237.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0238.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0239.jpg",
    "width": 1024,
    "height": 683
  },
  {
    "src": "/images/client-showroom/photo-0240.jpg",
    "width": 900,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0241.jpg",
    "width": 960,
    "height": 502
  },
  {
    "src": "/images/client-showroom/photo-0242.jpg",
    "width": 1125,
    "height": 844
  },
  {
    "src": "/images/client-showroom/photo-0243.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0244.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0245.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0246.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0247.jpg",
    "width": 715,
    "height": 413
  },
  {
    "src": "/images/client-showroom/photo-0248.jpg",
    "width": 960,
    "height": 632
  },
  {
    "src": "/images/client-showroom/photo-0249.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0250.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0251.jpg",
    "width": 1134,
    "height": 850
  },
  {
    "src": "/images/client-showroom/photo-0252.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0253.jpg",
    "width": 1600,
    "height": 1066
  },
  {
    "src": "/images/client-showroom/photo-0254.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0255.jpg",
    "width": 1600,
    "height": 1093
  },
  {
    "src": "/images/client-showroom/photo-0256.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0257.jpg",
    "width": 1174,
    "height": 880
  },
  {
    "src": "/images/client-showroom/photo-0258.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0259.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0260.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0261.jpg",
    "width": 1024,
    "height": 576
  },
  {
    "src": "/images/client-showroom/photo-0262.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0263.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0264.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0265.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0266.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0267.jpg",
    "width": 480,
    "height": 320
  },
  {
    "src": "/images/client-showroom/photo-0268.jpg",
    "width": 680,
    "height": 453
  },
  {
    "src": "/images/client-showroom/photo-0269.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0270.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0271.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0272.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0273.jpg",
    "width": 542,
    "height": 596
  },
  {
    "src": "/images/client-showroom/photo-0274.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0275.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0276.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0277.jpg",
    "width": 960,
    "height": 614
  },
  {
    "src": "/images/client-showroom/photo-0278.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0279.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0280.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0281.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0282.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0283.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0284.jpg",
    "width": 1334,
    "height": 750
  },
  {
    "src": "/images/client-showroom/photo-0285.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0286.jpg",
    "width": 1134,
    "height": 850
  },
  {
    "src": "/images/client-showroom/photo-0287.jpg",
    "width": 1174,
    "height": 880
  },
  {
    "src": "/images/client-showroom/photo-0288.jpg",
    "width": 900,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0289.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0290.jpg",
    "width": 1254,
    "height": 1254
  },
  {
    "src": "/images/client-showroom/photo-0291.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0292.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0293.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0294.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0295.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0296.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0297.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0298.jpg",
    "width": 1600,
    "height": 937
  },
  {
    "src": "/images/client-showroom/photo-0299.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0300.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0301.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0302.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0303.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0304.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0305.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0306.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0307.jpg",
    "width": 900,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0308.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0309.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0310.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0311.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0312.jpg",
    "width": 1125,
    "height": 689
  },
  {
    "src": "/images/client-showroom/photo-0313.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0314.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0315.jpg",
    "width": 960,
    "height": 640
  },
  {
    "src": "/images/client-showroom/photo-0316.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0317.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0318.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0319.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0320.jpg",
    "width": 1215,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0321.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0322.jpg",
    "width": 683,
    "height": 911
  },
  {
    "src": "/images/client-showroom/photo-0323.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0324.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0325.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0326.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0327.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0328.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0329.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0330.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0331.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0332.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0333.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0334.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0335.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0336.jpg",
    "width": 1286,
    "height": 857
  },
  {
    "src": "/images/client-showroom/photo-0337.jpg",
    "width": 1350,
    "height": 1080
  },
  {
    "src": "/images/client-showroom/photo-0338.jpg",
    "width": 1092,
    "height": 675
  },
  {
    "src": "/images/client-showroom/photo-0339.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0340.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0341.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0342.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0343.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0344.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0345.jpg",
    "width": 480,
    "height": 320
  },
  {
    "src": "/images/client-showroom/photo-0346.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0347.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0348.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0349.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0350.jpg",
    "width": 792,
    "height": 374
  },
  {
    "src": "/images/client-showroom/photo-0351.jpg",
    "width": 1600,
    "height": 1067
  },
  {
    "src": "/images/client-showroom/photo-0352.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0353.jpg",
    "width": 1600,
    "height": 818
  },
  {
    "src": "/images/client-showroom/photo-0354.jpg",
    "width": 1600,
    "height": 757
  },
  {
    "src": "/images/client-showroom/photo-0355.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0356.jpg",
    "width": 1174,
    "height": 880
  },
  {
    "src": "/images/client-showroom/photo-0357.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0358.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0359.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0360.jpg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/images/client-showroom/photo-0361.jpg",
    "width": 1134,
    "height": 850
  },
  {
    "src": "/images/client-showroom/photo-0362.jpg",
    "width": 1024,
    "height": 682
  },
  {
    "src": "/images/client-showroom/photo-0363.jpg",
    "width": 800,
    "height": 533
  },
  {
    "src": "/images/client-showroom/photo-0364.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0365.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0366.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0367.jpg",
    "width": 1600,
    "height": 1067
  },
  {
    "src": "/images/client-showroom/photo-0368.jpg",
    "width": 1200,
    "height": 1600
  },
  {
    "src": "/images/client-showroom/photo-0369.jpg",
    "width": 1600,
    "height": 900
  },
  {
    "src": "/images/client-showroom/photo-0370.jpg",
    "width": 1200,
    "height": 1600
  }
];
